var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/dashboardAdmin/propiedades/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8076a11f._.js")
R.c("server/chunks/ssr/node_modules_05136449._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_4891526f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7a3f9f34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_(admin)_dashboardAdmin_layout_tsx_2b8804ec._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d180f5e6._.js")
R.c("server/chunks/ssr/_30b5719b._.js")
R.c("server/chunks/ssr/_03841656._.js")
R.m(79831)
R.m(40481)
module.exports=R.m(40481).exports
