var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(private)/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8076a11f._.js")
R.c("server/chunks/ssr/node_modules_05136449._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_4891526f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7a3f9f34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_(private)_dashboard_layout_tsx_76624982._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c9740d73._.js")
R.c("server/chunks/ssr/_30b5719b._.js")
R.c("server/chunks/ssr/_f61303ef._.js")
R.m(84972)
R.m(82341)
module.exports=R.m(82341).exports
