var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fe4a33d8._.js")
R.c("server/chunks/ssr/node_modules_05136449._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_4891526f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7a3f9f34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/[root-of-the-server]__779aa2cd._.js")
R.c("server/chunks/ssr/_30b5719b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_39f85e7e._.js")
R.m(57665)
R.m(50053)
module.exports=R.m(50053).exports
