// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/favoritos" | "/dashboard/mis-solicitudes" | "/dashboard/notificaciones" | "/dashboard/perfil" | "/dashboard/preferencias" | "/dashboardAdmin" | "/dashboardAdmin/notificaciones" | "/dashboardAdmin/perfil" | "/dashboardAdmin/propiedades" | "/dashboardAdmin/propiedades/[id]" | "/dashboardAdmin/propiedades/nueva" | "/dashboardAdmin/solicitudes" | "/dashboardAdmin/usuarios" | "/dashboardAdmin/usuarios/[id]" | "/login" | "/preview-ui" | "/properties" | "/properties/[id]" | "/publicar" | "/register" | "/servicios/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/dashboardAdmin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/dashboard/favoritos": {}
  "/dashboard/mis-solicitudes": {}
  "/dashboard/notificaciones": {}
  "/dashboard/perfil": {}
  "/dashboard/preferencias": {}
  "/dashboardAdmin": {}
  "/dashboardAdmin/notificaciones": {}
  "/dashboardAdmin/perfil": {}
  "/dashboardAdmin/propiedades": {}
  "/dashboardAdmin/propiedades/[id]": { "id": string; }
  "/dashboardAdmin/propiedades/nueva": {}
  "/dashboardAdmin/solicitudes": {}
  "/dashboardAdmin/usuarios": {}
  "/dashboardAdmin/usuarios/[id]": { "id": string; }
  "/login": {}
  "/preview-ui": {}
  "/properties": {}
  "/properties/[id]": { "id": string; }
  "/publicar": {}
  "/register": {}
  "/servicios/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/dashboardAdmin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
