// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(admin)/dashboardAdmin/notificaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/notificaciones">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/notificaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/perfil">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/propiedades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/propiedades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/propiedades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/propiedades/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/propiedades/nueva">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/propiedades/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/propiedades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/propiedades">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/propiedades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/solicitudes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/solicitudes">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/solicitudes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/usuarios/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/usuarios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/usuarios/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/dashboardAdmin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboardAdmin/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/favoritos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/favoritos">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/favoritos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/mis-solicitudes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mis-solicitudes">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/mis-solicitudes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/notificaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notificaciones">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/notificaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/perfil">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/preferencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/preferencias">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/preferencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/publicar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publicar">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/publicar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/properties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/properties/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/properties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/properties">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/servicios/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/servicios/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-ui/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-ui">> = Specific
  const handler = {} as typeof import("../../src/app/preview-ui/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(admin)/dashboardAdmin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboardAdmin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/dashboardAdmin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(private)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(private)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(user)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(user)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
